### PR TITLE
made compatible with python2

### PR DESCRIPTION
**Pull request by d3v-null**
ported uniqidmodule.c to uniqid.py and changed setuptools.setup()
arguments if in python2

### CODE REVIEW

**Comment by ghost** [comment]
Nice. I'll let this settle for a day or two and then review it.

**Comment by ghost** [comment]
Um. I forgot that this existed.

I'm actually really busy for the next bit of time, mind emailing me in 2 weeks or so?

**Comment by d3v-null** [comment]
haha sure, no worries

Derwent, 
Web Developer
laserphile.com http://dev.laserphile.com/

**Comment by d3v-null** [comment]
Hey, it’s been 2 weeks :D

Derwent, 
Web Developer
laserphile.com http://dev.laserphile.com/

**Comment by ghost** [comment]
Also see commit 9900d44e277a17db8376b2a427e89b9403485f4f

**Comment by d3v-null** [comment]
Cheers!

Derwent, 
Web Developer
laserphile.com http://dev.laserphile.com/

**Pull request merged**
